In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

from sklearn.pipeline import Pipeline, make_pipeline

from sklearn.preprocessing import OneHotEncoder,PowerTransformer, StandardScaler, MinMaxScaler

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

import pickle
import warnings
warnings.filterwarnings('ignore')

In [53]:
df=pd.read_csv("D:\INeuron\Full Stack data science\Coding\ML\Job_Project\Model_ready_data.csv",index_col=0)
df.head()

day  month  Temperature    RH    Ws  Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0  1.0    6.0         29.0  57.0  18.0  0.00  65.70  3.4   7.6  1.3  3.4  0.5   
1  2.0    6.0         29.0  61.0  13.0  1.25  64.40  4.1   7.6  1.0  3.9  0.4   
2  3.0    6.0         26.0  82.0  21.5  1.25  47.74  2.5   7.1  0.3  2.7  0.1   
3  4.0    6.0         25.0  89.0  13.0  1.25  47.74  1.3   6.9  0.0  1.7  0.0   
4  5.0    6.0         27.0  77.0  16.0  0.00  64.80  3.0  14.2  1.2  3.9  0.5   

   Classes  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0

In [54]:
df=df.astype({'day':int, 'month':int,'Classes':int})
df.head()

day  month  Temperature    RH    Ws  Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0    1      6         29.0  57.0  18.0  0.00  65.70  3.4   7.6  1.3  3.4  0.5   
1    2      6         29.0  61.0  13.0  1.25  64.40  4.1   7.6  1.0  3.9  0.4   
2    3      6         26.0  82.0  21.5  1.25  47.74  2.5   7.1  0.3  2.7  0.1   
3    4      6         25.0  89.0  13.0  1.25  47.74  1.3   6.9  0.0  1.7  0.0   
4    5      6         27.0  77.0  16.0  0.00  64.80  3.0  14.2  1.2  3.9  0.5   

   Classes  
0        0  
1        0  
2        0  
3        0  
4        0

In [55]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [56]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

# Logistic Classification

In [57]:
logistic=LogisticRegression()
logistic_model=logistic.fit(X_train,y_train)
pred=logistic_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)


Accuracy Score: 0.9864864864864865
Confusion_Matrix:
 [[27  0]
 [ 1 46]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        27
           1       1.00      0.98      0.99        47

    accuracy                           0.99        74
   macro avg       0.98      0.99      0.99        74
weighted avg       0.99      0.99      0.99        74



# DecisionTreeClassifier

In [58]:
DCT_CL=DecisionTreeClassifier()
DCT_CL_model=DCT_CL.fit(X_train,y_train)
pred=DCT_CL_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 0.972972972972973
Confusion_Matrix:
 [[26  1]
 [ 1 46]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96        27
           1       0.98      0.98      0.98        47

    accuracy                           0.97        74
   macro avg       0.97      0.97      0.97        74
weighted avg       0.97      0.97      0.97        74



# Random Forest Classifier

In [59]:
RF_CL=RandomForestClassifier()
RF_CL_model=RF_CL.fit(X_train,y_train)
pred=RF_CL_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 1.0
Confusion_Matrix:
 [[27  0]
 [ 0 47]]
Classification_Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       1.00      1.00      1.00        47

    accuracy                           1.00        74
   macro avg       1.00      1.00      1.00        74
weighted avg       1.00      1.00      1.00        74



# AdaBoostClassifier

In [60]:
AB_CL=AdaBoostClassifier()
AB_CL_model=AB_CL.fit(X_train,y_train)
pred=AB_CL_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 0.9594594594594594
Confusion_Matrix:
 [[26  1]
 [ 2 45]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.93      0.96      0.95        27
           1       0.98      0.96      0.97        47

    accuracy                           0.96        74
   macro avg       0.95      0.96      0.96        74
weighted avg       0.96      0.96      0.96        74



# GradientBoostingClassifier

In [61]:
GB_CL=GradientBoostingClassifier()
GB_CL_model=GB_CL.fit(X_train,y_train)
pred=GB_CL_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 0.9594594594594594
Confusion_Matrix:
 [[26  1]
 [ 2 45]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.93      0.96      0.95        27
           1       0.98      0.96      0.97        47

    accuracy                           0.96        74
   macro avg       0.95      0.96      0.96        74
weighted avg       0.96      0.96      0.96        74



# Support Vector Classifier

In [62]:
SVC_CL=SVC()
SVC_CL_model=SVC_CL.fit(X_train,y_train)
pred=SVC_CL_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 0.918918918918919
Confusion_Matrix:
 [[24  3]
 [ 3 44]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.89      0.89      0.89        27
           1       0.94      0.94      0.94        47

    accuracy                           0.92        74
   macro avg       0.91      0.91      0.91        74
weighted avg       0.92      0.92      0.92        74



# GaussianNB

In [63]:
NB_CL=GaussianNB()
NB_CL_model=NB_CL.fit(X_train,y_train)
pred=NB_CL_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 0.9459459459459459
Confusion_Matrix:
 [[26  1]
 [ 3 44]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.90      0.96      0.93        27
           1       0.98      0.94      0.96        47

    accuracy                           0.95        74
   macro avg       0.94      0.95      0.94        74
weighted avg       0.95      0.95      0.95        74



# KNeighborsClassifier

In [64]:
KN_CL=KNeighborsClassifier()
KN_CL_model=KN_CL.fit(X_train,y_train)
pred=KN_CL_model.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 0.918918918918919
Confusion_Matrix:
 [[23  4]
 [ 2 45]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.92      0.85      0.88        27
           1       0.92      0.96      0.94        47

    accuracy                           0.92        74
   macro avg       0.92      0.90      0.91        74
weighted avg       0.92      0.92      0.92        74



# Create a loop to form a dictionary based on the model prediction results

In [65]:
models_list=[LogisticRegression(),DecisionTreeClassifier(),RandomForestClassifier(),AdaBoostClassifier(),GradientBoostingClassifier(),SVC(),GaussianNB(),KNeighborsClassifier()]

predict_result=pd.DataFrame(columns=['Model_name','Accuracy_score'])

def prediction(X_train,y_train,X_test,y_test):
    for i in range(len(models_list)):
        current_model=models_list[i]
        model_fit=current_model.fit(X_train,y_train)
        pred=model_fit.predict(X_test)
        acc_score=accuracy_score(y_test,pred)
        conf_mat=confusion_matrix(y_test,pred)
        clf_report=classification_report(y_test,pred)

        print("MODEL_NAME:",current_model)
        print("-------------------------------------------")
        print("Accuracy Score:",acc_score)
        print("Confusion_Matrix:\n",conf_mat)
        print("Classification_Report:\n",clf_report)
        print("==============================================================================================================================")

        predict_result.loc[len(predict_result.index)]=[str(models_list[i]),round(acc_score*100,2)]


    print("----------------------------------------------------------------------------------------------------------------------------------")

    print(predict_result)


prediction(X_train,y_train,X_test,y_test)

MODEL_NAME: LogisticRegression()
-------------------------------------------
Accuracy Score: 0.9864864864864865
Confusion_Matrix:
 [[27  0]
 [ 1 46]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        27
           1       1.00      0.98      0.99        47

    accuracy                           0.99        74
   macro avg       0.98      0.99      0.99        74
weighted avg       0.99      0.99      0.99        74

MODEL_NAME: DecisionTreeClassifier()
-------------------------------------------
Accuracy Score: 0.9864864864864865
Confusion_Matrix:
 [[27  0]
 [ 1 46]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        27
           1       1.00      0.98      0.99        47

    accuracy                           0.99        74
   macro avg       0.98      0.99      0.99        74
weighted avg       0.99      0.99      0.99      

In [66]:
Top_models=predict_result[predict_result['Accuracy_score']==predict_result['Accuracy_score'].max()]
Top_models

Model_name  Accuracy_score
0      LogisticRegression()           98.65
1  DecisionTreeClassifier()           98.65
2  RandomForestClassifier()           98.65

# Peform the Best Model Fit

In [102]:
model_name=Top_models['Model_name'].iloc[0]
model=eval(model_name)

best_model=model
best_model_fit=best_model.fit(X_train,y_train)
pred=best_model_fit.predict(X_test)
acc_score=accuracy_score(y_test,pred)
conf_mat=confusion_matrix(y_test,pred)
clf_report=classification_report(y_test,pred)

print("Accuracy Score:",acc_score)
print("Confusion_Matrix:\n",conf_mat)
print("Classification_Report:\n",clf_report)

Accuracy Score: 0.9864864864864865
Confusion_Matrix:
 [[27  0]
 [ 1 46]]
Classification_Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        27
           1       1.00      0.98      0.99        47

    accuracy                           0.99        74
   macro avg       0.98      0.99      0.99        74
weighted avg       0.99      0.99      0.99        74



# Create a Pcikle File with the best model

In [86]:
import pickle
pickle_filename=model_name.replace("()","")
pickle.dump(best_model,open(f"{pickle_filename}.pkl",'wb'))

# Load Pickle File

In [87]:
pickle_model=pickle.load(open(f"{pickle_filename}.pkl",'rb'))

#Batch Input to gt the batch predicted output
pickle_model.predict(X_test)

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1])

In [88]:
single_input=[list(X_test.iloc[73,:].values)]
single_input

[[30.0, 6.0, 33.0, 50.0, 14.0, 0.0, 88.7, 22.9, 92.8, 7.2, 28.3, 12.9]]

In [120]:
pickle_model.predict(single_input)[0]

1

In [121]:
pickle_model.predict([[2,6,29.0,61.0,13.0,1.25,64.40,4.1,7.6,1.0,3.9,0.4]])[0]

0

In [103]:
X_test

day  month  Temperature    RH    Ws  Rain  FFMC   DMC      DC   ISI  \
24    25      6         31.0  64.0  15.0   0.0  86.7  14.2   63.80   5.7   
6      7      6         33.0  54.0  13.0   0.0  88.2   9.9   30.50   6.4   
155    2      7         33.0  48.0  16.0   0.0  87.6   7.9   17.80   6.8   
213   29      8         35.0  53.0  17.0   0.5  80.2  20.7  149.20   2.7   
200   16      8         40.0  41.0  10.0   0.1  92.0  22.6   65.10   9.5   
..   ...    ...          ...   ...   ...   ...   ...   ...     ...   ...   
167   14      7         37.0  37.0  18.0   0.2  88.9  12.9   14.69  12.5   
156    3      7         34.0  56.0  17.0   0.1  84.7   9.7   27.30   4.7   
218    3      9         28.0  75.0  16.0   0.0  82.2   4.4   24.30   3.3   
79    19      8         35.0  62.0  19.0   0.0  89.4  23.2  120.90   9.7   
29    30      6         33.0  50.0  14.0   0.0  88.7  22.9   92.80   7.2   

      BUI   FWI  
24   18.3   8.4  
6    10.9   7.2  
155   7.8   6.4  
213  30.6   5.9  
200  24.2  14.8  
..    ...   ...  
167  10.4  10.5  
156  10.3   5.2  
218   6.0   2.5  
79   31.3  17.2  
29   28.3  12.9  

[74 rows x 12 columns]